version: "3.8"
services:
    #tarot-cards:
    constilations:
      build: ./s3-constalations
      ports:
      - target: 5001
        published: 5001
        protocol: tcp
    #combination:
    frontend:
      build: ./s1-front-end
      ports:
      - target: 5000
        published: 5000
        protocol: tcp
      
    #nginx:
    #    image: nginx:latest
    #    ports:
    #    - target: 80
    #      published: 80
    #      protocol: tcp
    #    volumes:
    #    - type: bind
    #      source: ./nginx/nginx.conf
    #      target: /etc/nginx/nginx.conf