all:
  hosts:
  children:
    managers:
      hosts:
        swarm-master:
    workers:
      hosts:
        swarm-worker:
        swarm-worker2:
    nginx:
      hosts:
        nginx-rplb:
  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    docker_users:
      - username: jenkins
        