---
# tasks file for worker
- name: "join swarm"
  community.docker.docker_swarm:
  state: join
  advertise_addr: "{{ inventory_hostname }}"
  join_token: "{{ hostvars['manager']['swarm_info][swarm_facts']['join_token']['worker'] }}"
  remote_addrs: [ "swarm-master:2377"]